export default {
    "island_ap": true,
    "island_ships_owner": true,
    "island_details": true,
    "world_search_island": true,
    "city_details": true,
    "city_building_tooltip": true,
    "dummy_resource_prod": true,
    "dummy_transporter": true,
    "units_max": true,
    "diplomacy_links": true,
    "diplomacy_tab_members": true,
    "diplomacy_fast_accept": true,
    "military_movements": true,
    "transport_buttons": true,
    "barbarian_auto_select_cargo_ships": true,
    "cinema_floating_player": true,
    "check_github_updates": true,
    "auto_accept_daily_bonus": true,
    "prevent_accidental_colony_destruction": true,
    "empire": true,
    "notes": false,
    "city_hotkeys": true,
    "quick_menu": false,

    "hide_premium": true,
    "hide_ads": true,
    "hide_happy_hour": false,
    "hide_friends_bar": false,

    "anticaptcha_key": "",

    "notification_wait_no_interaction": true,
    "notification_building_complete": true,
    "notification_building_complete_prevent": false,
    "notification_recruiting_complete": true,
    "notification_transport_loading": false,
    "notification_transport_en_route": true,
    "notification_transport_returning": true,
    "notification_advisor": false
}
